# Definition for CI within GitLab
# Note:
#    Prefix any job name with a '.' to disable.
#


# Enable submodules
variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none


# Common definitions for the jobs
.common: &common
  artifacts:
    when: always
    paths:
      - FanController/rm32
      - FanController/built/docs
  dependencies: []


#### Builds ####
build-command-riscos:
  <<: *common
  stage: build
  script:
    - xsltproc --version || { apt-get update && apt-get install -y xsltproc ; }
    - cd FanController
    - riscos-amu ram BUILD32=1
    - riscos-amu docs BUILD32=1
  tags:
    - riscos


#### Stages to execute ####
stages:
  - build
